config/routes.rb
Quickstream::Application.routes.draw do
  get "home/index"

  get "home/intro"

  get "home/play"
  
  resource :facebook, :except => :create do
    get :callback, :to => :create
  end  
  
  match 'facebooks/:id/save_phone' => 'facebooks#save_phone'

  match 'call/call' => 'call#call'
  match 'call/sms' => 'call#sms'
  
  

  root :to => 'home#index'

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :facebook
  has_many :songs
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def intro
  end

  #POST home/play
  def play
    # identifiers = params[:friend_tokens].split(",")
    # friend_list = current_user.friends.reject {|item| !identifiers.include? item.identifier}
    common_artist = Hash.new
    # friend_list.each do |friend|
    #   user = FbGraph::User.fetch(friend.identifier, :access_token => friend.access_token)
    #   user.music.each do |music|
    #     #if music.category == "Musician/band"
    #       if common_artist.has_key? music.name
    #         common_artist[music.name] += 1
    #       else
    #         common_artist[music.name] = 1
    #       end
    #     #end
    #   end  
    # end
    # 
    # current_user.music.each do |music|
    #   #if music.category == "Musician/band"
    #     if common_artist.has_key? music.name
    #       common_artist[music.name] += 1
    #     else
    #       common_artist[music.name] = 1
    #     end
    #   #end
    # end
    # 
    
    if (params[:query])
      common_artist[params[:query]] = 6
    
      sort_common_artists  = common_artist.sort_by {|key, values| -1*values}
      
      @playlist_title = params[:query]
            
      @tracklist = Array.new  
      counter = 0
      sort_common_artists.take(30).each do |pair|
        begin
          # c = Curl::Easy.perform("http://ws.spotify.com/search/1/track.json?q=#{CGI.escape pair[0].to_s}") # FROM SPOTIFY 
          c = Curl::Easy.perform("http://tinysong.com/s/#{CGI.escape pair[0].to_s.sub(" ","+")}?format=json&limit=#{[32,2**pair[1]-1].min}&key=186bd60f3a33be26da02d62d334bddf4") # FROM Tinysong      
        rescue
          next
        end
        parsed_json = ActiveSupport::JSON.decode(c.body_str)
        # parsed_json['tracks'].each do |track| # FOR SPOTIFY
        parsed_json.each do |track| # FOR TINYSONG
          # count = 0 # FOR SPOTIFY
          check = false
          @tracklist.each do |item|
            check = (item[0].downcase == track['SongName'].downcase)
            break if check
          end
          next if check
          # @tracklist << [track['name'], "http://open.spotify.com/track/" + track['href'][14..track['href'].length]] # FOR SPOTIFY
          @tracklist << [track['SongName'], track['ArtistName'], track['Url'], track['SongID']] # FOR TINYSONG
          counter += 1
          break if counter == 30
          # count += 1 # FOR SPOTIFY
          # break if count == 2**pair[1]-1 # FOR SPOTIFY
        end
        break if counter == 30
      end

      # @tracklist.each do |track| # FOR SPOTIFY
      #     begin
      #       c = Curl::Easy.perform("http://tinysong.com/b/#{CGI.escape track[0].to_s.sub(" ","+")}?format=json&key=186bd60f3a33be26da02d62d334bddf4") # FOR SPOTIFY
      #     rescue
      #       next
      #     end
      #   parsed_json = ActiveSupport::JSON.decode(c.body_str) # FOR SPOTIFY
      #   track << parsed_json['SongID'] # FOR SPOTIFY
      # end # FOR SPOTIFY
    else
      @tracklist = Array.new
      playlist = Playlist.find(params[:playlist_id].to_i)
      playlist.songs.each do |track| # FOR TINYSONG
        @tracklist << [track.name, track.artist, track.url, track.tinysong_id] # FOR TINYSONG
      end
      # @playlist_title = playlist.name
      # c = Curl::Easy.http_post("https://graph.facebook.com/#{params[:user]}/quickstream:listen_to",
      #                          Curl::PostField.content('playlist', "http://quickstream.heroku.com/home/play?playlist_id=#{params[:playlist_id]}"),
      #                          Curl::PostField.content('access_token', 'AAAC3O7zjCaYBALJEKSRZCZAA4UbMDNksd0JRiMybumZCPfvum4dEduZCEw5JNH246lt9Atzqw4yddBhvJBIhQyf1rkSYTD0ZCrJYkoKWiU93UOkpCNnEZB'))
      # 
      # puts "HEREEEE" + c.body_str                         
      
    end    
    
  	respond_to do |format|
       format.html # play.html.erb
    end

  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div id="main" role="main">
  <div class="wrapper">

	<% if authenticated? %>
		<%= form_tag("facebooks/#{current_user.id}/save_phone/", :remote => true) do %>
			<%= text_field_tag :phone, nil, :placeholder => 'Enter your phone number' , :value => (current_user.cell.gsub('+1','') if current_user.cell) %> <br/>
			<%= submit_tag "Save", :class => "button grey play" %>
		<% end %>
		<p> Use voice command (like Siri on iPhone) to text our app at <span class="strong">(949) 272-0608</span> with following commands: </p>
		
		<p>	To play songs text 'play' followed by the name of the song/artist you want to listen to. </p>

		<p>	To play a playlist text 'play playlist' followed by the name of the playlist you want to listen to. </p>

		<p>	To create a playlist text 'create' followed by the name of the playlist you want to create </p>

		<p>	To add a song to a playlist text 'add' followed by the name of the song you want to add followed
				by 'to' and then the name of the playlist you'd like to add it to. </p>
				
		<p> Add our number <span class="strong">(949) 272-0608</span> under <span class="strong">Quick Stream</span> to your contacts for easy access </p>
				

	<% else %>
        <P style="font-size: 150%"><span class="strong">QuickStream</span> allows you to voice command your music on the  <span class="strong">fly</span>.</p>
	<p></p>
		<%= link_to "Connect with facebook", new_facebook_path, :class => "button blue" %>
        <hr class="divider"/>
        <a href="#" class="button grey">Take a tour</a>
      </div>

	<% end %>

  </div>
</div>

app/views/home/intro.html.erb
<h1>Home#intro</h1>
<p>Find me in app/views/home/intro.html.erb</p>

app/views/home/play.html.erb
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# quickstream: http://ogp.me/ns/fb/quickstream#">
 <meta property="fb:app_id"      content="201467199949222" /> 
 <meta property="og:type"        content="quickstream:playlist" /> 
 <meta property="og:url"         content="<%= "http://quickstream.heroku.com" + request.fullpath %>" /> 
 <meta property="og:title"       content="<%= @playlist_title %>" /> 
 <meta property="og:description" content="" /> 
 <meta property="og:image"       content="https://s-static.ak.fbcdn.net/images/devsite/attachment_blank.png" />

<%song_ids = []%>
<% @tracklist.each do |track| %> 
	<% song_ids << track[3].to_s%>
<%end%>
<div id="container">
	<div id="main" style="text-align: center;">
		<object align="center" style="padding-top: 10px" width="250" height="<%= [250 + ((@tracklist.count/4)-1)*75, 600].min %>" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" id="gsManySongs31673607280782744" name="gsManySongs31673607280782744">
			<param name="movie" value="http://grooveshark.com/widget.swf" />
			<param name="wmode" value="window" /><param name="allowScriptAccess" value="always" />
			<param name="flashvars" value="hostname=cowbell.grooveshark.com&songIDs=<%= song_ids.join(',') %>&bbg=4a8f2c&bth=4a8f2c&pfg=4a8f2c&lfg=4a8f2c&bt=FFFFFF&pbg=FFFFFF&pfgh=FFFFFF&si=FFFFFF&lbg=FFFFFF&lfgh=FFFFFF&sb=FFFFFF&bfg=666666&pbgh=666666&lbgh=666666&sbh=666666&p=1" />
			<!--[if !IE]>-->
			<object type="application/x-shockwave-flash" data="http://grooveshark.com/widget.swf" width="250" height="<%= [250 + ((@tracklist.count/4)-1)*75, 600].min %>">
				<param name="wmode" value="window" /><param name="allowScriptAccess" value="always" /><param name="flashvars" value="hostname=cowbell.grooveshark.com&songIDs=<%= song_ids.join(',') %>&bbg=4a8f2c&bth=4a8f2c&pfg=4a8f2c&lfg=4a8f2c&bt=FFFFFF&pbg=FFFFFF&pfgh=FFFFFF&si=FFFFFF&lbg=FFFFFF&lfgh=FFFFFF&sb=FFFFFF&bfg=666666&pbgh=666666&lbgh=666666&sbh=666666&p=1" />
				</object>
				<!--<![endif]-->
				</object>

<br />
<br />
<fb:like href="<%= "http://quickstream.heroku.com" + request.fullpath %>" send="true" width="323" show_faces="true" ></fb:like>
<br />

<hr style="border: none; border-bottom-color: rgba(0, 0, 0, 0.1); box-shadow: 0 1px 0 #fff;"/>
<h2>Open in <!-- Spotify -->Grooveshark!</h2>
<hr style="border: none; border-bottom-color: rgba(0, 0, 0, 0.1); box-shadow: 0 1px 0 #fff;"/>

<% @tracklist.each do |track| %> 
	<%= link_to track[0].to_s + " - " + track[1].to_s, track[2].to_s, :class => 'track' %>
	<br />
<%end%>
	</div>
</div>

<%= @parsed_json.to_s %>